server:
  port: 8080
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.76.128.254:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: ryl123
huaweiyun:
  obs:
    access-key: MTMDAN7TXAWZWLU6TRAS
    secret-key: V4Z1LKGjQXEsCV99VN7TM2sXMo34QnXEHHCXdXo1
    end-point: https://obs.cn-east-2.myhuaweicloud.com
mybatis-plus:
  mapper-locations: classpath*:com\ryl\res\mapper\**\*.xml
