server:
  port: 8088
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://120.76.128.254:3306/test?useUnicode=true&characterEncoding=utf8&allowMultiQueries=true
    username: root
    password: ryl123
  servlet:
    multipart:
      max-request-size: 100MB
      max-file-size: 500MB
  redis:
    port: 6379
    host: 120.76.128.254
    timeout: 10000
    password: ryl123
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: root
    password: ryl123
    #虚拟host 可以不设置,使用server默认host
    virtual-host: /ryl
    publisher-confirm-type: correlated  # 消息发送确认,必须配置这个才会确认回调
    publisher-returns: true  # 开启发送失败退回
    listener:
      simple:
        acknowledge-mode: manual
        prefetch: 2 # 一次请求中预处理的消息数量
        concurrency: 1 # 消费端最小并发数(同一个队列启动几个消费者)
        max-concurrency: 5 # 消费端最大并发数(同一个队列最多启动几个消费者)
        retry:
          enabled: true
          max-attempts: 5
          stateless: false
          multiplier: 1.0
          initial-interval: 1000ms
          max-interval: 10000ms
        default-requeue-rejected: false
  jackson:
  generator:
    parent: com.ryl
    module: res
#jwt:
#  header-key:
#  secret:
#  expire-time:
#  token-prefix-type:
#  claims-key:
#  jwt-subject:

mybatis-plus:
  mapper-locations: classpath*:com\ryl\res\mapper\**\*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
logback:
  level: debug
  path: /opt/product
  layout: '%d{YY-mm-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n'
swagger:
  group-name: 资源中心
  base-package: com.ryl.res.controller
  title: 资源中心 API
  description: luoluodafang
  version: 1.0.0
  contact-name: yongliang.ren
  contact-url:
  contact-email: 1017632646@qq.com
huaweiyun:
  obs:
    access-key: MTMDAN7TXAWZWLU6TRAS
    secret-key: V4Z1LKGjQXEsCV99VN7TM2sXMo34QnXEHHCXdXo1
    end-point: https://obs.cn-east-2.myhuaweicloud.com
    bucket-name: obs-621e